# circleci does not support version 3.3 ~
version: "3.2"
services:
  app:
    container_name: "gobel-api"
    build:
        context: "./app"
        dockerfile: "Dockerfile.ci"
    ports:
      - "8080:8080"
    command: ./app